"""Adding user model

Revision ID: 53484f47a8b3
Revises: 
Create Date: 2023-05-18 16:16:18.170333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53484f47a8b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=330), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('fullname', sa.String(length=1000), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
