version: '3'
services:
  web:
    build:
      context: .
    container_name: sp
    ports:
    - "8080:8080"
    volumes:
    - ./app:/app
    environment:
      - PYTHONPATH=/app
      - FLASK_APP=.
    links:
    - db
    depends_on:
      - db
  db:
    image: postgres
    container_name: sp_db
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"
